build:
  image: golang:1.7
  commands:
    - go get github.com/pointlander/peg
    - go get github.com/shurcooL/vfsgen
    - go generate
    - go get -v
    - go build -v
    - go test -v -coverprofile=coverage.txt
    - go tool cover -func=coverage.txt
